export const ROUTES = {
    HOME: '/',
    PROYECTOS: '/proyectos',
    PROYECTO_DETALLE: '/proyectos/:id',
    NOSOTROS: '/nosotros',
    EVENTOS: '/eventos',
    EVENTO_DETALLE: '/eventos/:id',
    NOTICIAS: '/noticias',
    NOTICIA_DETALLE: '/noticias/:id',
    GALERIA: '/galeria',
    MAPA: '/mapa',
    CERROS: '/cerros',
    CERRO_DETALLE: '/cerros/:id',
    LOGIN: '/login',
    REGISTER: '/register',
    VOLUNTARIADO: '/voluntariado',
    FAQ: '/preguntas-frecuentes',
    CONTRIBUCIONES: '/contribuciones',
} as const;
